// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC262-dMotQf4w0ISPvJjkwjMZGaKguYJE',
    appId: '1:935225444330:web:1680466ac1c39b7cb71493',
    messagingSenderId: '935225444330',
    projectId: 'global-gaming-cb19c',
    authDomain: 'global-gaming-cb19c.firebaseapp.com',
    storageBucket: 'global-gaming-cb19c.firebasestorage.app',
    measurementId: 'G-9ZLDJEMPHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZAMiPaU0rOPO9CBPH4GbGfpjWU6p8IS4',
    appId: '1:935225444330:android:e1db86a067a67740b71493',
    messagingSenderId: '935225444330',
    projectId: 'global-gaming-cb19c',
    storageBucket: 'global-gaming-cb19c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3uFV5IO1n_u-Uymz2HeMtxAKcSHcU_aM',
    appId: '1:935225444330:ios:722a02e1ea097161b71493',
    messagingSenderId: '935225444330',
    projectId: 'global-gaming-cb19c',
    storageBucket: 'global-gaming-cb19c.firebasestorage.app',
    iosBundleId: 'com.example.projectGlobalGaming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3uFV5IO1n_u-Uymz2HeMtxAKcSHcU_aM',
    appId: '1:935225444330:ios:722a02e1ea097161b71493',
    messagingSenderId: '935225444330',
    projectId: 'global-gaming-cb19c',
    storageBucket: 'global-gaming-cb19c.firebasestorage.app',
    iosBundleId: 'com.example.projectGlobalGaming',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC262-dMotQf4w0ISPvJjkwjMZGaKguYJE',
    appId: '1:935225444330:web:7a7903bd6ca31886b71493',
    messagingSenderId: '935225444330',
    projectId: 'global-gaming-cb19c',
    authDomain: 'global-gaming-cb19c.firebaseapp.com',
    storageBucket: 'global-gaming-cb19c.firebasestorage.app',
    measurementId: 'G-J9G1X8W5BY',
  );
}
